#!/bin/bash

./script/cmake-build simulation -DOT_FULL_LOGS=ON -DOT_LOG_OUTPUT=PLATFORM_DEFINED -DOT_LOG_LEVEL=NONE -DOT_SIMULATION_MAX_NETWORK_SIZE=200 -DOT_APP_CLI=ON -DOT_FTD=ON -DOT_MTD=OFF -DOT_APP_NCP=OFF -DOT_APP_RCP=OFF -DOT_RCP=OFF
